name: 'K8S Deployer'
author: 'David Gamote'
description: 'Deploy your project to Kubernetes without any hassle'

branding:
  icon: 'anchor'
  color: 'blue'

inputs:
  namespace:
    description: 'Kubernetes namespace name. (Required)'
    required: true
  releaseName:
    description: 'Helm release name. Will be combined with track if set. (Required)'
    required: true
  chart:
    description: 'Helm chart. (Required)'
    required: true
  helmVersion:
    description: 'Version of Helm. Installs a specific version of Helm binary (Default: latest?)'
    required: false
  values:
    description: 'Helm chart override values, expected to be a YAML or JSON string.'
    required: false
  valueFiles:
    description: 'Additional value files to apply to the Helm chart. Expects JSON encoded array or a string.'
    required: false
  repoUrl:
    description: 'Helm chart repository to be added.'
    required: false
  repoName:
    description: 'Helm repository alias that will be used.'
    required: false
  wait:
    description: 'Helm --wait flag. Defaults to true'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
